[tool.poetry]
name = "wirebus"
version = "0.1.0"
description = ""
authors = ["taejun-song <songtj10@snu.ac.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
